name: Build and Deploy a Drawing-Canva React App
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run build --no-verify
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
